ValueError: Use cause() to establish the name of the function that caused the error and prepend it to the message
Also update tests that were affected by this change.