ValueError: Don't auto-prefix function name if prefix includes ':' colon
(The reason a prefix would include a colon is likely because function name has been baked into the prefix itself.)